image: maven:3.6.3-jdk-8

java:
  stage: test
  script:
    "mvn clean verify"
  artifacts:
    when: always
    paths:
      - target/site/serenity
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
